services:
  league-app:
    container_name: league-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    environment:
      VITE_APP_AUTH_URL: "http://keycloak-dev:8082/"
      VITE_APP_AUTH_REALM: "probe-app"
      VITE_APP_AUTH_CLIENTID: "probe-app-client"
      VITE_APP_FOOTBALL_APIURL: "http://localhost:19081/api/q/v1/"
    extra_hosts:
      - "keycloak-dev:host-gateway"    
    ports:
      - "31021:80"
    restart: unless-stopped
